/* Prompts and activity banks: daily journal prompts plus art, music, nature, project, game, and PE banks (Oct 2026 - Jul 2027). */
(function (root) {
  'use strict';
  var C = typeof require !== 'undefined' && typeof module !== 'undefined' ? require('./core.js') : root.Content;
  var Q = C.Q, T = C.T;

  // ============================ JOURNAL ============================
  // One per school day, in calendar order: fall first, Christmas around 35-45,
  // Easter and spring around 90-100, summer near the end. Kinds are mixed so
  // similar prompts are spread out.
  C.prompts.journal = [
    // ---- Fall (October - November) ----
    "Fall is here in Georgia. Use all five senses to describe a fall afternoon outside. What do you see, hear, smell, taste, and feel? Try to write at least one sentence for each sense.",
    "Tell about the best day you can remember. Where were you, who was with you, and what happened from beginning to end? Explain why that day stands out to you.",
    "What if you woke up and could understand what animals were saying? Which animal would you talk to first, and what would you ask it? Write the conversation you think you would have.",
    "Is it better to be a morning person or a night person? Pick one side and give at least three reasons that support your opinion.",
    "Write a thank-you letter to God for three things in your life that you are grateful for right now. Tell why each one matters to you and how it shows His care.",
    "Explain how to make your favorite snack, step by step. Pretend the reader has never been in a kitchen before, so leave nothing out. Use order words like first, next, then, and finally.",
    "Think about a time a friend was kind to you. What did they do, and how did it make you feel? How could you do something like that for someone else this week?",
    "What is one thing you want to get better at before Christmas? Write your goal, why it matters to you, and three small steps you can take to reach it.",
    "Imagine a pumpkin patch that comes alive at night. What do the pumpkins do after the farmer goes to sleep? Write a short story with a beginning, a middle, and an end.",
    "Write a letter to a grandparent or another older relative. Tell them what you have been learning and doing lately, and ask them two questions about when they were your age.",
    "Leaves change color in the fall. Describe your favorite tree right now. What colors are its leaves, what does the bark feel like, and what sounds does it make in the wind?",
    "Should kids be allowed to choose their own bedtime? Give your opinion and at least three reasons. Then write one thing someone who disagrees with you might say.",
    "Describe your bedroom so well that someone could draw it without ever seeing it. Include where things are, what colors you see, and the one object that matters most to you.",
    "Tell about a time you were brave, even though you felt scared. What happened, what were you afraid of, and how did you feel afterward?",
    "What if you could shrink to the size of an ant for one day? Where would you go, what would you see, and what dangers would you need to watch out for?",
    "Think about a person in your church or your family who helps others. What do they do? Write about how their example shows love, and what you could learn from them.",
    "Explain how to play your favorite game so that a new player could learn it from your writing. Include the goal, the rules, and one tip for winning.",
    "Which season in Georgia is the best: fall, winter, spring, or summer? Choose one and convince the reader with strong reasons and examples.",
    "Write about your earliest memory. How old were you, and what do you remember seeing, hearing, or feeling? Why do you think this memory stuck with you?",
    "Imagine you are a squirrel getting ready for winter in a Georgia backyard. Write a day in your life. Where do you hide your acorns, and who tries to find them?",
    "What makes someone a good friend? List at least four qualities and explain each one with an example from real life or from a book.",
    "Describe a meal that your family loves. What does it smell like while it cooks, how does it taste, and who usually makes it? Tell about a time you all ate it together.",
    "If you could invent a new holiday, what would it celebrate? Describe what people would eat, wear, and do on that day, and why the world needs it.",
    "Write a letter to yourself to open one year from now. Tell your future self what you like right now, what you are working on, and what you hope will be true by then.",
    "Think about a time you made a mistake and someone forgave you. What happened? How did being forgiven feel, and how does it help you understand God's forgiveness?",
    "Explain how to take care of a pet, a plant, or a younger child for one day. What do they need, and what should someone never forget to do?",
    "Is it better to live in the city or in the country? Pick one and give at least three reasons. Use details about Georgia if you can.",
    "Tell about a trip you have taken, near or far. How did you get there, what did you do, and what was the most surprising part?",
    "Imagine a door appears in the trunk of an old oak tree. You open it and step inside. Describe the world you find and what happens next.",
    "Thanksgiving is coming. Make a list of ten things you are thankful for, then pick two of them and write a few sentences about why each one is a gift.",
    "Describe a Thanksgiving table using all five senses. What foods are there, what do people say, and what does the room sound and smell like?",
    "Write a thank-you note to someone who has helped you learn something this fall. Tell them exactly what they did and how it helped you.",
    "What is the hardest thing you have learned to do so far this school year? Explain why it was hard and what you did to keep going.",
    "If you could ask a person from Georgia history one question, who would you ask and what would you say? Explain why you chose that person.",
    // ---- Winter and Christmas (December) ----
    "December is here. What are your favorite family traditions for the Christmas season? Describe one of them in detail, and explain why it is special to you.",
    "Imagine you were a shepherd on the hillside the night Jesus was born. Describe what you saw and heard, and how you felt when you went to find the baby. (You can read Luke 2 for ideas.)",
    "Explain how to wrap a present neatly, step by step. Include the materials you need and one mistake to avoid.",
    "Describe the smell, sound, and look of your house during the Christmas season. Is there a candle, a tree, cookies, or music? Paint a picture with words.",
    "Is it more fun to give a gift or to get a gift? Share your opinion and give reasons. Tell about a gift you gave that made someone happy.",
    "Write a letter to someone you will not see this Christmas. Tell them your news, wish them a merry Christmas, and tell them something you remember about them.",
    "What if it snowed two feet in your town overnight? Describe the day: what you would do, what you would wear, and how the neighborhood would look and sound.",
    "Why do you think God chose to send Jesus as a tiny baby instead of as a king in a palace? Write your thoughts and explain your reasons.",
    "Think about someone who might feel lonely at Christmas. How could you show them kindness this week? Write a plan with at least three ideas.",
    "Tell about your favorite Christmas memory. Who was there, what happened, and what made it so special?",
    "The year is almost over. What are three things you learned this year that you are proud of? Explain how you learned each one.",
    // ---- Winter (January - March) ----
    "A new year is starting. Write three goals for this year: one for school, one for your family, and one for your heart or faith. Explain how you will work on each one.",
    "Imagine you could visit any place in the world for one week. Where would you go, how would you get there, and what would you do each day?",
    "Describe a cold winter morning in Georgia. What does the frost look like on the grass, how does the air feel, and what sounds do you hear?",
    "Explain how to build a fort out of blankets and pillows. Include the materials, the steps, and how to make it strong enough not to fall down.",
    "Should every kid learn to play a musical instrument? Give your opinion with at least three reasons. Then tell which instrument you would choose and why.",
    "Tell about a time you felt left out. What happened, and how did you handle it? What would you say to another girl who feels that way?",
    "What if you could talk to a character from your favorite book? Who would it be, what would you ask, and what do you think they would answer?",
    "Write a letter to a missionary, a soldier, or a nurse you may not know. Thank them for their work and tell them a little bit about yourself.",
    "Think of a time when you prayed about something. What were you praying for, and what happened? How do you feel when you talk to God?",
    "Describe your favorite place in your house to read. What does it look like, what does it feel like to sit there, and what makes it cozy?",
    "Is homework or practice ever fun? Give your opinion and support it with reasons and examples from your own school days.",
    "Tell about a time you laughed so hard you could not stop. What was so funny? Try to tell it so the reader laughs too.",
    "Imagine you invented a robot to help around the house. What does it look like, what jobs does it do, and what goes wrong on its first day?",
    "What are five things that make your family special? Write about each one, and give an example that shows it.",
    "Explain how to make a bed or fold laundry the right way. Write clear steps and tell why it is worth doing well.",
    "Brown thrashers, cardinals, and Carolina wrens stay in Georgia all winter. Pick a bird you have seen and describe it: its colors, its size, its song, and what it was doing.",
    "Which is better: reading a book or watching the movie? Choose a side and back it up with reasons and an example of a story you know both ways.",
    "Tell about something you made with your own hands. What was it, how did you make it, and what would you do differently next time?",
    "What if you were the teacher for one whole day? What would you teach, what games would you play, and what rules would you have?",
    "Write about a person who makes you feel safe and loved. What do they do or say? Write them a short note at the end telling them thank you.",
    "God made every person different on purpose. What are three things that make you, you? Explain how each of those things could be used to help others.",
    "Describe a rainy day using all five senses. What does the rain sound like on the roof, what does the yard smell like, and what do you like to do inside?",
    "If you could have any job when you grow up, what would it be? Explain what the job involves, why you would be good at it, and what you would need to learn first.",
    "Think about a time you and a friend or sibling disagreed. What happened, how did you solve it, and what did you learn about getting along?",
    "Imagine you found a message in a bottle on a Georgia beach. What does the message say, who wrote it, and what do you do next?",
    "Explain how to take care of your teeth, hair, or skin each day. Write the steps clearly and tell why each step matters.",
    "Should children have a job or chores at home? Give your opinion and three reasons, and describe the chores you think are fair.",
    "Write a letter to your favorite author. Tell them which book you liked, what part you loved most, and a question you would like to ask them.",
    "Tell about a time you got hurt or sick. What happened, who took care of you, and how did you feel when you got better?",
    "What if animals could vote? Which animal would run for president, what would it promise, and who would vote for it?",
    "Describe your favorite outfit. What does it look like, how does it feel to wear it, and where do you like to wear it? Why does it make you feel good?",
    "Name a promise God makes in the Bible that means a lot to you, or a Bible story you love. Retell it in your own words and explain why it matters to you.",
    "Think about a hero in your life, someone you look up to. What makes them a hero? Give at least three examples of things they have done.",
    "Explain how to draw a simple animal, step by step, so someone could follow your directions without seeing a picture.",
    "Georgia has mountains in the north and beaches in the south. Would you rather spend a week in the North Georgia mountains or on the Georgia coast? Explain your choice with reasons.",
    "Tell about your favorite birthday so far. What did you do, who celebrated with you, and what made it special?",
    "Imagine you are a raindrop falling from a cloud over Georgia. Tell the story of where you land and where you travel next.",
    "What is something you used to be afraid of but are not anymore? Explain what changed and how you got braver.",
    "What does it mean to be a good listener? Explain with examples, and write about a time someone really listened to you.",
    "Write a how-to guide for a new kid who is starting homeschool. What should they know about your school day, and what tips would help them?",
    "Spring is coming. Describe the first signs of spring you have noticed in your yard or neighborhood. Look for buds, birds, bugs, and blooms.",
    "If you could be famous for one thing, what would it be? Explain why you chose it and how you would use your fame to help others.",
    "Tell about a time someone surprised you. What was the surprise, how did you find out, and how did you react?",
    // ---- Spring and Easter (late March - April) ----
    "Dogwood trees bloom white and pink across Georgia in early spring. Describe a blooming tree or flower using as many senses as you can.",
    "Easter is coming. Retell the story of the first Easter morning in your own words, as if you were one of the women who went to the tomb. (You can read Matthew 28 or John 20 for ideas.)",
    "Explain how to plant a seed and help it grow. Include the materials, the steps, and what the plant needs every day.",
    "What if every day were a holiday? Would that be great or terrible? Give your opinion and explain what would happen.",
    "Write about what Easter means to your family. What do you do to celebrate, and what does Jesus rising from the dead mean to you?",
    "Write a letter to a younger child explaining why spring is a wonderful season. Give them three things to look for outside.",
    "Tell about a time you helped someone without being asked. What did you do, and how did it make both of you feel?",
    "Imagine you are a bee visiting flowers in a Georgia garden. Describe your busy day and the flowers you visit.",
    "Should people spend more time outside than they do? Give your opinion and support it with at least three reasons.",
    "Describe a spring rainstorm: the sky before it starts, the sound of thunder, the smell of wet earth, and how everything looks afterward.",
    "What new beginning are you thankful for this spring? It might be a new skill, a new friend, or a new habit. Explain how it started and why it matters.",
    // ---- Late spring (April - May) ----
    "Tell about a time you won something or reached a goal. What did you have to do to get there, and how did it feel?",
    "If you could design the perfect playground, what would it include? Describe each part and explain why kids would love it.",
    "Explain how to be a good friend to someone who is new. Write at least five steps or tips and explain each one.",
    "Is it better to have one best friend or lots of good friends? Share your opinion and explain your reasons.",
    "Write a letter to your mom or dad telling them about three things they do that you appreciate. Be specific.",
    "Imagine you are an explorer in the Okefenokee Swamp. Describe what you see, hear, and smell as you paddle your canoe through the black water.",
    "Think about a time you had to wait patiently for something. What were you waiting for, how did it feel, and what did waiting teach you?",
    "Describe your favorite animal as if you were a scientist writing a report. Where does it live, what does it eat, and what makes it amazing?",
    "What if you could fly for one hour? Where would you go first, what would you see below you, and how would it feel?",
    "Tell about a family member who taught you something important. What did they teach you, and how do you use it now?",
    "Explain how to make a sandwich, a smoothie, or another simple food. Give exact steps and amounts so anyone could make it.",
    "Choose a rule in your house and tell whether you think it is a good rule. Explain why, and suggest one change if you think it needs one.",
    "Psalm 19 says the sky shows how great God is. Go outside and look up. Describe the sky, the clouds, or the stars, and write what it makes you think about God.",
    "Describe a sound you love and a sound you cannot stand. Explain what each one reminds you of and how it makes you feel.",
    "If you could have dinner with anyone from history, who would it be? What would you ask them, and what do you think you would learn?",
    "Tell about a time you were proud of someone else. What did they do, and how did you let them know?",
    "Imagine your stuffed animals or toys came to life while you were asleep. What adventure would they have, and what would you find in the morning?",
    "What are three ways you can be kind online, on the phone, or in a text or video call? Explain why kindness matters even when you cannot see someone's face.",
    "Write a how-to guide for having the perfect Saturday. What would you do in the morning, afternoon, and evening?",
    "Should zoos exist? Think about what is good and what is hard about zoos for animals and people. Then share your opinion with reasons.",
    "Describe a walk you took recently. Where did you go, what did you notice along the way, and how did you feel at the end?",
    "What is a goal you set earlier this year? Write about how it is going, what has helped, and what you could do to finish strong.",
    "Write a letter to a friend you have not seen in a while. Tell them what you have been up to and ask about their life.",
    "Think of a time when you felt God was with you, even if you could not see Him. What happened, and how did you know?",
    "Tell about a time you learned something new from a mistake. What went wrong, what did you figure out, and what do you do differently now?",
    "What if you could switch places with your mom or dad for one day? Describe what you would do, what would be hard, and what you would learn about their job.",
    "Is it better to be good at many things or great at one thing? Choose a side and support it with at least three reasons.",
    "Explain how to care for a bicycle, scooter, or favorite toy so it lasts a long time. Give clear steps and tell what happens if you skip them.",
    "Describe the inside of a grocery store or farmers market using all five senses. Which smells, colors, and sounds stand out the most?",
    "Write a letter to a girl your age who lives in another country. Tell her about life in Georgia and ask her three questions about her home.",
    "The Bible says we can do good to others even when it is hard. Write about someone who is not always easy to be kind to, and plan one kind thing you can do for them.",
    "Think about a friend who is very different from you. What do you each like, and how do your differences make the friendship better?",
    "Imagine you are a pine tree that has stood in a Georgia forest for one hundred years. What have you seen and heard? Tell your story.",
    "Tell about a time you were really, really excited. What were you excited about, how did you show it, and did it turn out the way you hoped?",
    "If you started a club, what would it be about? Explain who could join, what you would do at meetings, and what rules the club would have.",
    "What is something you are curious about and want to learn more about? Write three questions you have and how you could find the answers.",
    "Write about a chore or job you do well. Explain how you learned it and why doing it well helps your family.",
    "Should kids your age have their own phone? Think about both sides, then give your opinion with clear reasons.",
    "Imagine a new animal that lives only in Georgia. What does it look like, what does it eat, and how does it survive in the forest, swamp, or mountains?",
    "Tell about the funniest thing a family member has ever done. Use details so the reader can picture it.",
    "Explain how to stay safe during a thunderstorm. List the steps and explain why each one matters.",
    "Which would you rather have: a pet dog, cat, bird, or fish? Pick one and give at least three reasons for your choice.",
    "Describe a place in nature that feels peaceful to you. What does it look, sound, and feel like? Why do you feel calm there?",
    "If you could change one thing about the world, what would it be? Explain why, and describe how life would be different.",
    "Write a thank-you letter to a helper in your community, like a mail carrier, firefighter, doctor, or librarian. Tell them how their work helps you.",
    "Tell about a time when you tried something new and it did not go how you expected. What happened, and what did you learn?",
    "What does it mean to be honest, even when it is hard? Give an example and explain why honesty matters to God and to others.",
    "Imagine you could travel back to a time in Georgia history. When would you go, what would you see, and what would surprise you most?",
    "Explain how to take care of a garden or a houseplant. What does it need, and what happens if you forget?",
    "Is it better to plan everything or to be spontaneous, which means doing things without a plan? Share your opinion with reasons and examples.",
    "Describe your family's car, porch, or kitchen during a busy morning. What is everyone doing, saying, and hearing?",
    "What is one way you can serve your family this week without being asked? Write your plan and how you think it will make them feel.",
    "Write a story about a girl who discovers she has a special talent. What is the talent, how does she find out, and how does she use it?",
    "Think about what makes a good leader. Write about someone you know who is a good leader and give examples of what they do.",
    "Tell about something you collect or would like to collect. How did you start, what is your favorite piece, and why do you like it?",
    "Write a prayer in your own words for someone you love. Tell God what they need and thank Him for them.",
    "What if there were no electricity for a whole week? How would your family cook, stay cool or warm, and have fun? Describe the week.",
    "Explain how to say sorry the right way. What should you say, what should you do, and why does a good apology matter?",
    "Describe the outside of your home so well that someone could find it. What colors, plants, and sounds would they notice?",
    "Should kids get to pick what the family eats for dinner one night a week? Give your opinion with reasons, and tell what you would pick.",
    "Tell about a time you were really, truly surprised by nature, like seeing a deer, a rainbow, a big storm, or a strange bug.",
    "Imagine you open a lemonade stand. What do you name it, how do you make the lemonade, what do you charge, and what happens on opening day?",
    "What are three things you have learned about yourself this school year? Explain how you learned each one.",
    "Write a letter to next year's version of you as you start 5th grade. Give yourself advice and encouragement.",
    "Think of a time you shared something that was hard to share. What was it, why was it hard, and how did you feel afterward?",
    "Explain how to get ready for a trip. Make a packing list and explain why each item belongs on it.",
    "School is almost out for the year. What are you most proud of from 4th grade? Describe it and explain why.",
    "Describe your favorite book character using details from the book. What do they look like, how do they act, and why do you like them?",
    "What if you could breathe underwater? Where would you explore first, and what creatures would you want to meet?",
    "Write about a hymn, worship song, or Bible verse that helps you when you feel worried or sad. Why does it help?",
    // ---- Summer (June - July) ----
    "Summer is here. Describe a hot Georgia summer day using all five senses: the sun, the sound of cicadas, cold water, and sweet fruit.",
    "Make a summer bucket list with at least ten things you want to do. Then pick the top three and explain why each one made the list.",
    "Fireflies light up Georgia yards on summer nights. Describe what it is like to watch or catch them, and tell why you think God made them glow.",
    "Should summer break be longer or shorter? Give your opinion with at least three strong reasons.",
    "Explain how to make the perfect glass of lemonade or sweet tea, or another cold summer drink. Include every step.",
    "Imagine you are a turtle on a Georgia beach. Tell the story of your journey from the sand to the ocean.",
    "Tell about a summer memory from last year. Where were you, what were you doing, and why do you remember it?",
    "Write a postcard-style letter to a friend telling them about your summer so far. Include three things you have done and one thing you are looking forward to.",
    "What does rest look like for you? Write about why rest matters, how God rested on the seventh day, and what helps you feel refreshed.",
    "Describe a summer thunderstorm rolling in on a hot afternoon. How does the air change, what does the sky look like, and what do you hear?",
    "If you could spend one day doing absolutely anything you wanted, what would you do from morning to night? Explain your choices.",
    "Think about a neighbor or friend you could help this summer. Write a plan for something kind you could do for them.",
    "Explain how to stay safe and cool on a very hot day. Write at least five tips and explain why each one helps.",
    "Is it better to go to the pool, the lake, or the beach? Choose one and convince the reader with reasons and details.",
    "Imagine you planted a magic seed in your backyard and it grew overnight. What grew, and what happened when you climbed it or picked it?",
    "The Fourth of July celebrates America's birthday. Describe how your family celebrates and explain what freedom means to you.",
    "Write a letter to God thanking Him for this school year. Tell Him about the hard parts, the happy parts, and what you hope for next year.",
    "Tell about the best book you read this year. What happened, who was your favorite character, and why would you recommend it?",
    "Look back at your journal. Which entry is your favorite and why? Write about how your writing has grown this year.",
    "What are three goals you have for 5th grade? Explain each one and what you will do to reach it.",
    "Describe yourself one year ago and yourself today. How have you grown on the outside and on the inside?"
  ];

  // ============================== ART ==============================
  C.prompts.art = [
    { title: "Draw a leaf three ways", how: "Collect one leaf from the yard. Draw it three times on one sheet of paper: once with pencil showing every vein, once with only bold outlines in marker, and once using only dots of colored pencil. Label which version you like best and why." },
    { title: "Crayon leaf rubbings", how: "Place a few leaves vein-side up under a sheet of thin paper. Peel the paper off old crayons and rub the side of the crayon over each leaf until the shape and veins appear. Try fall colors like orange, red, and gold, and overlap the leaves to make a pattern." },
    { title: "Self-portrait in a mirror", how: "Sit in front of a mirror with a pencil and paper. Lightly draw an oval for your face, then look closely and add your eyes about halfway down, your nose, mouth, and hair. Take your time and look at the mirror more than the paper, then add color with colored pencils." },
    { title: "Watercolor sunset sky", how: "Wet a sheet of watercolor or thick paper with a clean brush. Paint stripes of yellow, orange, pink, and purple across the paper and watch the colors blend into each other. When it is dry, use a black marker to draw pine tree shapes along the bottom like a Georgia evening." },
    { title: "Still life of fruit", how: "Set two or three pieces of fruit on a plate near a window. Draw them in pencil, paying attention to where the light hits and where the shadows fall, and shade the darker sides. Finish with colored pencils, pressing lightly for light areas and harder for shadows." },
    { title: "Paper-plate stained glass", how: "Cut the center out of a paper plate to make a frame. Tape clear plastic wrap or wax paper across the hole and glue on small pieces of colored tissue paper to make a cross, a sun, or a flower. Hang it in a sunny window and watch the light shine through." },
    { title: "Draw with only shapes", how: "Draw a house, a cat, and a tree using only circles, squares, triangles, and rectangles. You may overlap shapes but not draw any curvy lines that are not part of a shape. Color it in bright markers when you finish." },
    { title: "Christmas card design", how: "Fold a sheet of cardstock in half. On the front, draw a nativity star, a candle, or a winter scene with colored pencils or markers, and leave space so it does not feel crowded. Write a short, kind message inside and give it to someone special." },
    { title: "Pointillism dot painting", how: "Pointillism is a way of painting with tiny dots of color instead of lines. Lightly sketch a simple flower or tree, then fill it in using only dots made with marker tips or cotton swabs dipped in paint. Step back from your picture and notice how the dots blend together." },
    { title: "Cardboard bird feeder art", how: "Draw a Georgia bird such as a cardinal or brown thrasher on a piece of cardboard and cut it out with an adult's help. Paint it with acrylic or tempera paint, adding details like a red crest or speckled chest. Punch a hole and hang it near a window." },
    { title: "Mixing your own colors", how: "Use only red, yellow, and blue paint plus white. Paint a color wheel by mixing the primary colors to make orange, green, and purple, then add white to make lighter tints. Label each color with what you mixed to make it." },
    { title: "Shadow tracing outside", how: "On a sunny morning, set a toy, a vase, or a plant on a sheet of paper outside. Trace its shadow with a pencil, then come back in two hours and trace the new shadow in a different color. Color in the shapes to make a design and notice how the shadow moved." },
    { title: "Clay or playdough sculpture", how: "Use air-dry clay or playdough to sculpt a small animal you have seen in Georgia, like a turtle, rabbit, or frog. Roll balls and coils for the body parts and press them together firmly, then use a toothpick to add texture. Let it dry and paint it if you used clay." },
    { title: "Draw a map of your neighborhood", how: "Use a large sheet of paper and colored pencils to draw a bird's-eye map of your street or neighborhood. Include houses, trees, roads, and your favorite places, and add a compass rose and a key. Make it neat enough that a visitor could use it." },
    { title: "Spring flower collage", how: "Cut flower shapes out of old magazines, colored paper, or wrapping paper. Glue them onto a sheet of cardstock to make a garden, overlapping petals and adding green paper stems and leaves. Add a sky and sun with crayon or marker." },
    { title: "Blind contour drawing", how: "Choose an object like your shoe or your hand. Draw it with a pen while looking only at the object and never at your paper, moving your pen slowly as your eyes follow the edges. The result will look funny, but this trains your eyes and hand to work together." },
    { title: "Easter sunrise painting", how: "Paint a sunrise with yellow and pink at the bottom of the page fading to blue at the top. When it is dry, cut out a black paper hill with three crosses or an empty tomb and glue it in front of the sky. Write the date on the back." },
    { title: "Symmetry butterfly print", how: "Fold a sheet of paper in half and open it again. Drop small blobs of paint on one side only, then fold the paper closed and press firmly, and open it to see a matching butterfly pattern. When it is dry, draw a body and antennae down the middle." },
    { title: "Zentangle name art", how: "Write your name in large bubble letters across a sheet of paper. Fill each letter with a different pattern, such as stripes, zigzags, dots, swirls, or tiny hearts, using a fine black pen. Add color to a few sections to make them pop." },
    { title: "Sketch a Georgia landscape", how: "Look at a photo of Stone Mountain, Amicalola Falls, or the Georgia coast, or look out your own window. Draw the scene in pencil with a horizon line, then add things that are far away smaller and higher on the page and things that are close larger and lower. Color it with crayons or colored pencils." },
    { title: "Draw your family as animals", how: "Choose an animal that fits each person in your family and draw everyone together as those animals. Give each animal a detail that shows the real person, like Dad's glasses or Mom's favorite color. Write a label explaining why you chose each animal." },
    { title: "Rock painting kindness stones", how: "Wash and dry a few smooth rocks. Paint them with acrylic paint and add simple pictures or kind words like 'You are loved' with a paint pen. Let them dry and leave them in your yard or give them to friends." },
    { title: "Fourth of July fireworks", how: "Dip the bottom of a toilet paper roll that has been cut into fringe into red, white, or blue paint. Press it onto dark blue or black paper to make bursts that look like fireworks. Add glitter or white crayon stars for sparkle." },
    { title: "Comic strip storytelling", how: "Fold a sheet of paper into four or six boxes. Draw a short comic about something funny that happened in your family, with speech bubbles for what each person says. Make sure the story has a beginning, a problem, and an ending." }
  ];

  // ============================= MUSIC =============================
  // Public-domain hymns and classical works only. No lyrics are included here.
  C.prompts.music = [
    { title: "Hymn: Amazing Grace", how: "Listen to a recording of 'Amazing Grace' and sing along. This hymn was written by John Newton, an Englishman who once worked on slave ships, turned away from that life, and later became a pastor who spoke out against slavery. Talk with a parent about what the word grace means and draw a picture of what the music makes you think of." },
    { title: "Hymn: Holy, Holy, Holy", how: "Listen to 'Holy, Holy, Holy' and notice how slow and strong the music feels. The words were written by Reginald Heber, an English pastor, and the tune most churches use was written by John Bacchus Dykes. Clap the steady beat while you listen, then sing along with the recording." },
    { title: "Hymn: Be Thou My Vision", how: "Listen to 'Be Thou My Vision.' The words come from a very old Irish poem that was translated into English about a hundred years ago, and the tune is an old Irish folk melody named 'Slane.' Find Ireland on a map, then sing along and hum the melody once on your own." },
    { title: "Hymn: It Is Well with My Soul", how: "Listen to 'It Is Well with My Soul.' Horatio Spafford wrote the words after a very sad loss in his family, and his friend Philip Bliss wrote the music. Talk with a parent about how someone can trust God even when life is hard, then sing along with a recording." },
    { title: "Hymn: Come Thou Fount", how: "Listen to 'Come Thou Fount of Every Blessing.' It was written in the 1700s by Robert Robinson when he was a young man in England. Sing along, then clap the rhythm of the first line and see if a parent can guess which line you are clapping." },
    { title: "Hymn: Fairest Lord Jesus", how: "Listen to 'Fairest Lord Jesus,' a hymn that comes from Germany and was first printed in the 1600s. While it plays, draw the beautiful things in nature that the music makes you think of, like meadows, the moon, or the sun. Then sing along with the recording." },
    { title: "Hymn: This Is My Father's World", how: "Listen to 'This Is My Father's World.' The words were written by Maltbie Babcock, a pastor who loved to take walks outside and enjoy God's creation. Take this hymn on a walk: hum it while you look for birds, trees, and flowers, then draw three things you saw." },
    { title: "Hymn: Joyful, Joyful, We Adore Thee", how: "Listen to 'Joyful, Joyful, We Adore Thee.' Henry van Dyke wrote the words in the early 1900s and set them to the 'Ode to Joy' melody from Beethoven's Ninth Symphony. Listen to the hymn first and then to the end of the symphony, and raise your hand when you hear the same tune." },
    { title: "Hymn: A Mighty Fortress", how: "Listen to 'A Mighty Fortress Is Our God,' written by Martin Luther in Germany in the 1500s. A fortress is a strong castle that keeps people safe. Draw a fortress while the music plays, then march to the strong, steady beat as you sing along." },
    { title: "Hymn: Crown Him with Many Crowns", how: "Listen to 'Crown Him with Many Crowns.' The tune most churches use was written by George Elvey, an English church organist. Make a paper crown and decorate it while you listen, then sing along with the recording and keep the beat by tapping your knees." },
    { title: "Hymn: Blessed Assurance", how: "Listen to 'Blessed Assurance.' The words were written by Fanny Crosby, who was blind for almost her whole life and wrote thousands of hymns. Her friend Phoebe Knapp played the tune on the piano, and Fanny wrote words to match it. Sing along, then talk about how Fanny did great things even with a challenge." },
    { title: "Hymn: What a Friend We Have in Jesus", how: "Listen to 'What a Friend We Have in Jesus.' Joseph Scriven first wrote the words as a poem to comfort his mother, who lived far away in Ireland. Sing along, then write a short note of comfort to someone you love." },
    { title: "Bach: Toccata and Fugue in D minor", how: "Listen to the opening of Johann Sebastian Bach's 'Toccata and Fugue in D minor,' played on a pipe organ. Bach was a German church musician who wrote a huge amount of music. Draw what you imagine while it plays, then talk about how the organ sounds different from a piano." },
    { title: "Bach: Jesu, Joy of Man's Desiring", how: "Listen to the music known in English as 'Jesu, Joy of Man's Desiring,' from a church piece by Bach. Notice the gentle melody that flows like water over a slower tune underneath. Move a ribbon or scarf to the flowing notes, then sit still and listen once more." },
    { title: "Vivaldi: Spring from The Four Seasons", how: "Listen to 'Spring' from 'The Four Seasons' by Antonio Vivaldi, an Italian composer and violinist. The violins imitate birds singing and a thunderstorm. Raise your hand each time you hear bird sounds, and draw a spring scene while the music plays." },
    { title: "Vivaldi: Winter from The Four Seasons", how: "Listen to 'Winter' from Vivaldi's 'The Four Seasons.' Listen for sharp, shivery notes that sound like teeth chattering and cold wind. Compare it with 'Spring' and write three words that describe how each one feels." },
    { title: "Mozart: Twinkle, Twinkle variations", how: "Listen to Mozart's twelve variations on the French song that has the same tune as 'Twinkle, Twinkle, Little Star.' A variation is the same tune changed in a new way: faster, fancier, or in a new mood. Count the variations as you listen and tell which one is your favorite." },
    { title: "Mozart: Eine kleine Nachtmusik", how: "Listen to the first part of Mozart's 'Eine kleine Nachtmusik,' which means 'a little night music' in German. Mozart began writing music when he was a small child. Conduct the music with a pencil as your baton, moving it up and down with the beat." },
    { title: "Beethoven: Symphony No. 5", how: "Listen to the opening of Beethoven's Fifth Symphony. Clap the famous short-short-short-long rhythm, then listen for how many times you hear it. Beethoven kept writing music even after he became deaf, so talk about how he might have heard the music in his mind." },
    { title: "Beethoven: Für Elise", how: "Listen to Beethoven's 'Für Elise,' one of the most famous piano pieces ever. Hum the opening melody until you can do it from memory. If you have a keyboard, try to find the first few notes by ear." },
    { title: "Handel: Hallelujah Chorus", how: "Listen to the 'Hallelujah' chorus from George Frideric Handel's 'Messiah,' a large work about the life of Jesus. Handel wrote the whole 'Messiah' in only about three weeks in 1741. Many audiences stand up during this chorus, so stand when it begins and count how many times you hear the word hallelujah." },
    { title: "Handel: Messiah for Christmas", how: "Listen to another part of Handel's 'Messiah,' such as the opening overture or a piece about the birth of Jesus. 'Messiah' was first performed in Dublin, Ireland, in 1742. Draw a picture of the Christmas story while you listen." },
    { title: "Tchaikovsky: Sugar Plum Fairy", how: "Listen to 'Dance of the Sugar Plum Fairy' from 'The Nutcracker' ballet by the Russian composer Pyotr Tchaikovsky. The tinkling sound comes from an instrument called the celesta, which looks like a small piano but sounds like bells. Tiptoe like a dancer to the music." },
    { title: "Tchaikovsky: Nutcracker March", how: "Listen to the 'March' from 'The Nutcracker.' Find the steady beat and march around the room, stopping when the music gets quiet. Then draw the toy soldiers or the Christmas party you imagine." },
    { title: "Clap the rhythm of a hymn", how: "Choose a hymn you know well, like 'Amazing Grace.' Clap the rhythm of the words while a recording plays, then clap it again without the recording and see if a parent can guess the hymn. Take turns clapping hymns and guessing." },
    { title: "Listen and draw: loud and soft", how: "Play any classical piece from this list. Draw big, dark lines when the music is loud and small, light lines when it is soft. Music words for loud and soft are forte and piano, so label your drawing with those words." },
    { title: "Make a homemade instrument", how: "Make a shaker by putting dried beans or rice in a plastic bottle and taping the lid on tight. Play along with a hymn recording, shaking on the beat. Try a second instrument, like a rubber band stretched across an open box, and compare the sounds." }
  ];

  // ============================= NATURE ============================
  C.prompts.nature = [
    { title: "Fall color hunt", how: "Take your nature journal and colored pencils to the yard or a park. Find leaves in as many colors as you can, like red maple, yellow hickory, and brown oak, and draw the three most different ones. Write the date and the weather at the top of the page." },
    { title: "Acorn and seed collection", how: "Collect acorns, pinecones, sweetgum balls, and other seeds on a walk. Sort them on a paper towel and draw each kind in your journal, labeling the tree it came from if you know. Write how you think each seed travels to a new place to grow." },
    { title: "Sit-spot listening", how: "Choose one spot outside and sit quietly for ten minutes with your journal. Make a sound map: put an X in the middle for yourself and draw small symbols for each sound you hear and the direction it came from. Write which sounds came from nature and which came from people." },
    { title: "Bird feeder watch", how: "Watch a bird feeder or a busy tree for fifteen minutes. Tally each bird you see, and use a bird guide or app to identify Georgia birds like cardinals, chickadees, titmice, and the brown thrasher, which is Georgia's state bird. Draw your favorite one in your journal." },
    { title: "Monarch and butterfly search", how: "Look for butterflies on flowers in the fall, when monarchs travel south through Georgia. Draw any butterfly you see, showing the pattern on its wings, and note what flower it was visiting. Never catch or touch the wings." },
    { title: "Tree bark rubbings", how: "Bring paper and a crayon outside. Press the paper against three different trees, such as a pine, an oak, and a sweetgum, and rub the crayon across to make bark prints. Glue them into your journal and describe how each bark feels." },
    { title: "Cloud watching journal", how: "Lie on a blanket and watch the clouds for ten minutes. Draw the clouds you see and label them: puffy cumulus, thin wispy cirrus, or flat gray stratus. Write what weather you think is coming and check the next day to see if you were right." },
    { title: "Adopt a tree", how: "Pick one tree near your home to visit once a month all year. Today, sketch the whole tree, a close-up of one leaf, and write its height compared to your house. Each visit, add the date and note what has changed." },
    { title: "Winter twig study", how: "In winter, look at the tips of bare branches for buds. Draw a twig up close, showing the buds and the scars where last year's leaves fell off. Predict what will grow from each bud in spring and check back in March." },
    { title: "Evergreen search", how: "On a winter walk, find plants that stay green all year, like pines, holly, magnolia, and cedar. Draw a needle or leaf from each one in your journal. Write why you think staying green might help a plant." },
    { title: "Animal tracks and signs", how: "After a rain, look in mud or soft dirt for animal tracks. Draw any tracks you find and measure them with a ruler, and look for other signs like chewed nuts, feathers, or holes. Write a guess about which animal left them." },
    { title: "Under a log or rock", how: "With an adult, gently roll over a log or large rock and look underneath. Draw the creatures you find, like pill bugs, earthworms, or beetles, without touching any you do not know. Carefully roll the log back exactly how you found it so the animals keep their home." },
    { title: "Spring bloom map", how: "Walk around your yard or neighborhood in early spring and find blooming plants like dogwood, redbud, azaleas, and daffodils. Draw a simple map and mark where each bloom is. Draw a close-up of one flower and count its petals." },
    { title: "Pollinator patrol", how: "Watch a flowering bush for ten minutes on a warm day. Tally the bees, butterflies, moths, and other insects that visit, and draw one of them. Watch from a respectful distance so you do not get stung." },
    { title: "Puddle and rain study", how: "After a rainstorm, go out with a ruler and your journal. Measure the depth of a puddle, draw its shape, and come back in a few hours to see how much it has shrunk. Write where you think the water went." },
    { title: "Red clay soil study", how: "Dig up a small scoop of soil from your yard with an adult's permission. Spread it on a paper plate and look closely with a magnifying glass for clay, sand, rocks, roots, and tiny creatures. Draw what you find and describe the color, since Georgia's red clay gets its color from iron in the soil." },
    { title: "Pine tree investigation", how: "Find a pine tree, which is one of the most common trees in Georgia. Count how many needles grow together in one bundle, draw a pinecone, and look for sap on the bark. Write three facts you observed with your own eyes." },
    { title: "Hummingbird watch", how: "In spring and summer, ruby-throated hummingbirds visit Georgia. Watch a feeder or flowers like trumpet vine for fifteen minutes and tally any visits. Draw the bird and describe how its wings move and sound." },
    { title: "Firefly evening", how: "On a warm summer evening, sit outside as it gets dark. Count how many fireflies you see in five minutes and draw the blinking pattern as dots and dashes. Write the time, the temperature, and whether it was humid." },
    { title: "Cicada and insect sounds", how: "On a summer afternoon, listen to the loud buzzing of cicadas in the trees. Look for their empty shells on tree trunks, and draw one if you find it. Write words that describe the sound, and compare the daytime insect sounds with the sounds at night." },
    { title: "Moon journal week", how: "For seven nights in a row, look at the moon at the same time and draw its shape in your journal. Label each drawing with the date. At the end of the week, write how the shape changed and whether it was growing or shrinking." },
    { title: "Creek or pond visit", how: "Visit a creek, pond, or lake with an adult. Sit at a safe spot on the bank and draw what you see in and around the water, like tadpoles, dragonflies, turtles, or water plants. Write how the water moves and what it sounds like." },
    { title: "Mushroom and fungus search", how: "After a few rainy days, look for mushrooms and fungus on logs, lawns, and tree trunks. Draw them carefully, noting their color, shape, and where they grow. Never touch or taste wild mushrooms, because some are poisonous." },
    { title: "Spider web hunt", how: "Early in the morning, look for spider webs in bushes and fences, especially when dew makes them sparkle. Draw the pattern of one web and note where it was built. Write why you think the spider chose that spot, and watch without touching." },
    { title: "Nature color palette", how: "Bring a paint chip card or a box of crayons outside. Try to find something in nature that matches each color, and write what you found next to it in your journal. Notice which colors are easy to find in this season and which are hard." },
    { title: "Weather station week", how: "For one week, record the weather each day at the same time: temperature from a thermometer, cloud cover, wind, and rain. Make a simple chart in your journal. At the end of the week, write about any pattern you notice." }
  ];

  // ============================ PROJECTS ===========================
  C.prompts.project = [
    { title: "Georgia state symbols booklet", how: "Day 1: Research Georgia's state symbols, such as the brown thrasher (bird), Cherokee rose (flower), and live oak (tree), and list them. Days 2-4: Make one page for each symbol with a drawing and two facts written in your own words. Day 5: Staple the pages together with a cover and read it to your family." },
    { title: "Build a bird feeder", how: "Day 1: Design a bird feeder using a milk jug, a plastic bottle, or a pinecone, and list the materials you need. Day 2: Build it with an adult's help, cutting openings and adding a perch. Day 3: Fill it with birdseed and hang it outside. Days 4-6: Watch it for ten minutes each day and record which birds come." },
    { title: "Family history interview", how: "Day 1: Write ten questions to ask a grandparent or older relative about their childhood. Day 2: Interview them in person or by phone and take notes. Day 3: Write a short biography of their life using your notes. Day 4: Add a drawing or photo and give them a copy." },
    { title: "Create a board game", how: "Day 1: Choose a theme, like a Georgia road trip or a Bible adventure, and sketch the board on paper. Day 2: Draw the final board on poster board or a cereal box. Day 3: Write question or challenge cards and make game pieces. Day 4: Write the rules, then play it with your family and fix anything that does not work." },
    { title: "Write and illustrate a picture book", how: "Day 1: Plan a story with a character, a problem, and a solution. Days 2-3: Write the story, about one or two sentences per page, for eight to ten pages. Days 4-6: Illustrate each page with colored pencils. Day 7: Make a cover and read it aloud to a younger child or your family." },
    { title: "Grow a bean plant journal", how: "Day 1: Place a dry bean in a wet paper towel inside a clear cup or zip bag and tape it in a sunny window. Days 2-10: Check it each day for five minutes, measure any growth, and draw it in a journal. When it has leaves, plant it in a pot of soil and keep watching." },
    { title: "Model of a Georgia region", how: "Day 1: Choose a Georgia region, such as the Blue Ridge mountains, the Piedmont, or the Coastal Plain, and research its land, plants, and animals. Day 2: Plan a model in a shoebox. Days 3-4: Build the land with clay or salt dough and paint it. Day 5: Add small paper animals and plants and write a label card." },
    { title: "Kindness project for neighbors", how: "Day 1: Make a list of neighbors or church friends who might like a surprise. Days 2-3: Make cards, bookmarks, or small crafts for each person. Day 4: Write a kind note in each one. Day 5: Deliver them with a parent and write in your journal about how it felt." },
    { title: "Cardboard marble run", how: "Day 1: Collect paper towel tubes, toilet paper rolls, and a big piece of cardboard. Day 2: Cut the tubes in half the long way and plan a path for a marble. Days 3-4: Tape the pieces to the cardboard on a slope and test the run, fixing spots where the marble falls off. Day 5: Time how long the marble takes and try to make it slower or faster." },
    { title: "Animal research poster", how: "Day 1: Pick an animal that lives in Georgia, like a gopher tortoise, black bear, or alligator, and find three good sources about it. Day 2: Take notes on its habitat, diet, and adaptations. Day 3: Plan and draw a poster with headings. Day 4: Finish the poster with facts in your own words and present it to your family." },
    { title: "Sew a simple pillow or pouch", how: "Day 1: With an adult's help, cut two matching squares of felt and thread a large needle. Days 2-3: Sew around three sides with a simple running stitch, keeping the stitches small and even. Day 4: Stuff it with cotton balls or fabric scraps and sew the last side closed. Day 5: Decorate it with buttons or fabric markers." },
    { title: "Bible timeline", how: "Day 1: List ten big events in the Bible in order, from Creation to the early church. Day 2: Tape several sheets of paper together into a long strip and draw a line across it. Days 3-5: Draw a small picture for each event and write a one-sentence summary in your own words. Day 6: Hang it on the wall and retell the story of the Bible to a parent." },
    { title: "Family cookbook", how: "Day 1: Ask family members for their favorite recipes and write them down. Days 2-4: Copy each recipe neatly onto its own page with ingredients and steps, and draw a picture of the finished food. Day 5: Make a cover and a table of contents. Day 6: Cook one recipe together with an adult." },
    { title: "Build a sundial", how: "Day 1: Learn how the sun's shadow moves across the sky during the day. Day 2: Push a pencil straight up through the center of a paper plate and set it on flat ground in a sunny spot. Day 3: Each hour, mark where the shadow falls and write the time. Day 4: Use your sundial to tell time and compare it to a clock." },
    { title: "Create a nature museum", how: "Days 1-2: Collect safe nature treasures like leaves, rocks, feathers you find on the ground, shells, and seeds. Day 3: Sort them into groups in an egg carton or shoebox. Day 4: Make a small label for each item saying what it is and where you found it. Day 5: Give your family a museum tour." },
    { title: "Make a newspaper for your family", how: "Day 1: Plan the sections, like family news, weather, a comic, and an interview. Days 2-3: Interview family members and write short articles. Day 4: Draw pictures and a comic strip. Day 5: Put it together on large paper and hand out copies at dinner." }
  ];

  // ============================== GAMES =============================
  C.prompts.game = [
    { title: "Multiplication War", how: "Use a regular deck of cards with face cards removed. Each player flips two cards and multiplies them, and the bigger product wins all the cards. When there is a tie, flip again, and the player with the most cards at the end wins." },
    { title: "Make Ten Go Fish", how: "Use cards Ace through 9, with Ace counting as 1. Instead of asking for a match, ask for the card that adds to yours to make 10, like asking for a 3 when you hold a 7. Lay down each pair that makes 10, and the player with the most pairs wins." },
    { title: "Twenty Questions", how: "One player thinks of a person, place, or thing. Everyone else takes turns asking yes-or-no questions, up to twenty total, to figure it out. Practice asking smart questions that cut the choices in half, like 'Is it alive?'" },
    { title: "Pig dice game", how: "You need one die and paper to keep score. On your turn, roll as many times as you like and add up the numbers, but if you roll a 1 you lose all the points from that turn. Decide when to stop and keep your points, and the first player to 100 wins." },
    { title: "Yahtzee or five-dice scoring", how: "Play Yahtzee with five dice and a score sheet, or make your own score sheet. Each turn, roll up to three times to try for combinations like three of a kind or a straight. Add your scores carefully and think about which box to use each turn." },
    { title: "Categories word game", how: "Pick a letter and set a timer for two minutes. Everyone writes a word for each category, such as an animal, a food, a city, and a girl's name, that starts with that letter. Score a point for each answer no one else wrote." },
    { title: "Chess or checkers night", how: "Play chess or checkers with a family member. Before each move, look at what your opponent could do next. After the game, talk about one smart move each player made." },
    { title: "Pictionary family drawing", how: "Write simple words on slips of paper, like 'tree,' 'birthday,' or 'Noah's ark,' and put them in a bowl. One player draws the word on paper or a whiteboard while the others guess, with a one-minute timer and no letters or numbers allowed. Take turns and keep score." },
    { title: "Battleship on graph paper", how: "Each player draws two 10-by-10 grids labeled with letters A-J across and numbers 1-10 down. Secretly place ships on one grid, then take turns calling coordinates like 'C7' to find each other's ships. This game practices coordinate grids." },
    { title: "Code Breaker logic game", how: "One player secretly writes a three-digit code using digits 1-6. The other guesses a code, and the code maker tells how many digits are right and in the right place, and how many are right but in the wrong place. Keep guessing until the code is cracked, then switch roles." },
    { title: "Story Chain storytelling", how: "Sit in a circle. One person starts a story with one sentence, and each person adds one sentence in turn. Try to give the story a clear problem and an ending before ten rounds are done." },
    { title: "Dominoes math match", how: "Play regular dominoes, matching ends with the same number of dots. For an extra challenge, score points whenever the open ends of the line add up to a multiple of five. Keep a running total on paper." },
    { title: "Memory card match", how: "Lay a deck of cards face down in a grid. Take turns flipping two cards, and keep them if they match in number. The player with the most pairs wins, so pay close attention to every flip." },
    { title: "Rummy card game", how: "Play rummy with a regular deck. Collect sets of three or four of the same number, or runs of three or more in order of the same suit. This game practices planning, sorting, and patterns." },
    { title: "Hangman spelling words", how: "Use words from this week's spelling list. One player draws blanks for each letter and the others guess letters, with a stick figure or a snowman drawn for each wrong guess. Talk about which letters are smart to guess first." },
    { title: "Connect Four strategy", how: "Play Connect Four, or draw a 7-column, 6-row grid on paper and use X and O. Take turns dropping a piece into a column, trying to get four in a row while blocking your opponent. Talk about strategy after each game." },
    { title: "Guess My Number", how: "One player thinks of a number from 1 to 100. The others guess, and the player answers 'higher' or 'lower' after each guess. Count the guesses, and try to find the number in seven guesses or fewer." },
    { title: "Bible Charades", how: "Write Bible stories on slips of paper, like David and Goliath or Jonah and the big fish. Take turns acting out a story without talking while everyone else guesses. Set a timer for one minute per turn." },
    { title: "Farkle dice game", how: "Use six dice and paper for scores. Roll all six dice and set aside scoring dice, such as 1s worth 100 points and 5s worth 50 points, then decide whether to roll again or keep your points. If a roll has no scoring dice, you lose that turn's points, and the first to 5,000 wins." },
    { title: "Tangram puzzle race", how: "Cut a square of cardboard into the seven tangram shapes, or use a tangram set. Take turns challenging each other to make a shape, like a cat or a boat, using all seven pieces. Time each player and celebrate creative solutions." },
    { title: "Would You Rather debate", how: "Take turns asking 'Would you rather' questions, like 'Would you rather live in the mountains or at the beach?' Each player must answer and give two reasons. This practices giving opinions with support." },
    { title: "Mancala counting game", how: "Play mancala with a board, or use an egg carton and 48 beans or small stones. Take turns picking up all the stones in one cup and dropping them one at a time into the cups going around. Count ahead to plan moves that land in your store." }
  ];

  // =============================== PE ==============================
  // About 20 minutes each, for one child, with little or no equipment.
  C.prompts.pe = [
    { title: "Animal walk relay", how: "Mark a start and finish line about 10 steps apart in the yard. Travel there and back as different animals: bear crawl, crab walk, frog jumps, and bunny hops. Rest and drink water between rounds." },
    { title: "Backyard obstacle course", how: "Build a course with things like pillows to jump over, a chair to crawl under, a rope or towel line to walk, and a tree to run around. Time yourself going through three times and try to beat your own time. Make sure the area is clear and safe." },
    { title: "Jump rope challenge", how: "Use a jump rope in a flat, open area. Count how many jumps you can do in one minute, rest, and try again three more times. Learn one new trick, like jumping on one foot or crossing your arms." },
    { title: "Ball wall toss", how: "Throw a tennis ball or soft ball against a wall or garage door and catch it. Try throwing with your right hand, then your left, then clapping once before catching. Count your catches in a row and try to break your record." },
    { title: "Dance party workout", how: "Play five upbeat songs and dance the whole time without stopping. During the chorus of each song, do a different move: jumping jacks, high knees, arm circles, or spinning. Cool down with a slow song and stretches." },
    { title: "Fitness dice", how: "Roll a die and do the matching exercise: 1 means 10 jumping jacks, 2 means 10 squats, 3 means 5 push-ups, 4 means 20 seconds of running in place, 5 means 10 lunges, and 6 means rest. Roll 20 times. Write down how many of each exercise you did." },
    { title: "Chalk hopscotch", how: "Draw a hopscotch board on the driveway or sidewalk with chalk. Toss a small stone into a square and hop through the board on one foot, skipping the square with the stone. Play several rounds and try making a new board shape." },
    { title: "Nature walk with speed bursts", how: "Go on a 20-minute walk with a parent around your neighborhood or a park. Every few minutes, choose a landmark like a mailbox or tree and speed-walk or jog to it. Drink water when you get home." },
    { title: "Yoga and stretching", how: "Lay a towel or mat on the floor. Hold each pose for five slow breaths: tree pose, mountain pose, cat-cow, downward dog, child's pose, and butterfly stretch. Go slowly and never stretch so far that it hurts." },
    { title: "Balloon keep-up", how: "Blow up a balloon and try to keep it from touching the floor using only your hands, then only your elbows, knees, and head. Count how many hits you can do in a row. Play in a room with plenty of open space." },
    { title: "Sidewalk chalk agility ladder", how: "Draw a ladder with ten boxes on the driveway with chalk. Run through it stepping in each box, then hop with two feet, then hop on one foot, then step side to side. Do each pattern three times." },
    { title: "Freeze dance", how: "Ask a parent or use a timer to stop the music at random times. Dance while the music plays and freeze like a statue when it stops. Try a different freeze pose each time and hold it still." },
    { title: "Hula hoop practice", how: "Practice keeping a hula hoop spinning around your waist and count how long you can go. Then try spinning it on one arm or using it as a jump rope. Lay it on the ground and hop in and out of it ten times." },
    { title: "Soccer dribble course", how: "Set up four or five cones, cups, or shoes in a line. Dribble a soccer ball in and out of them using gentle touches, then dribble back with your other foot. Finish by kicking the ball at a target, like between two trees." },
    { title: "Bike or scooter ride", how: "Put on your helmet and ride your bike or scooter for 20 minutes with an adult nearby. Practice stopping quickly, riding in a straight line, and making slow turns. Stay on safe paths away from traffic." },
    { title: "Superhero training", how: "Pretend you are training to be a superhero. Do 10 'power jumps' (squat jumps), 10 'shield pushes' (push-ups on knees are fine), 30 seconds of 'flying' (lying on your belly with arms and legs lifted), and a 'super sprint' across the yard. Repeat three rounds." },
    { title: "Frisbee or flying disc toss", how: "Practice throwing a flying disc against a fence or to a parent. Work on flicking your wrist so the disc flies flat. Set up a target, like a laundry basket, and see how many times you can land the disc in or near it from different distances." },
    { title: "Stair or step workout", how: "Use a single sturdy step or the bottom stair. Step up and down 20 times, leading with your right foot and then your left. Add calf raises on the step, holding a rail for balance, and rest between sets." },
    { title: "Simon Says fitness", how: "Have a parent or sibling lead Simon Says with movements like 'touch your toes,' 'do five jumping jacks,' and 'balance on one foot.' Only move when the leader says 'Simon says.' Then switch and be the leader." },
    { title: "Balance challenge", how: "Practice balancing on one foot for 30 seconds, then the other. Try it with your eyes closed, while holding a book on your head, or while walking on a line drawn on the ground with chalk. Have a wall nearby to catch yourself." },
    { title: "Red light, green light sprints", how: "Have a parent call out 'green light' for running, 'yellow light' for walking, and 'red light' for freezing. Play across the yard and back several times. This helps with listening, speed, and stopping safely." },
    { title: "Kick ball target practice", how: "Set up empty plastic bottles or cans like bowling pins. Kick a ball from a set distance to knock them down, then step back for a harder shot. Count how many you knock over in ten kicks." },
    { title: "Shadow tag and shadow moves", how: "On a sunny day, try to step on your own shadow, or play shadow tag with a family member. Then make your shadow do jumping jacks, wave, and dance. Notice how your shadow's size changes when you face toward or away from the sun." },
    { title: "Jumping jack countdown", how: "Do 50 jumping jacks, then 40 high knees, 30 butt kicks, 20 squats, and 10 star jumps. Rest for one minute, drink water, and repeat if you can. Count out loud as you go." },
    { title: "Sprinkler or water play", how: "On a hot summer day, put on a swimsuit and run through a sprinkler. Jump over the water, run in circles, and try to dodge it. Wear sunscreen and drink plenty of water." },
    { title: "Leaf pile jumping", how: "In the fall, rake leaves into a big pile, which is a good workout by itself. Then run and jump into the pile, check for sticks first, and rake it back up. Repeat until your 20 minutes are up." },
    { title: "Plank and core challenge", how: "Hold a plank on your forearms for 20 seconds, then a side plank on each side for 15 seconds. Do 10 slow sit-ups and 10 bicycle kicks. Rest and repeat two more times, keeping your back straight." },
    { title: "Walk and pray", how: "Take a 20-minute walk around your yard or neighborhood with a parent. At each corner or landmark, pause to pray for a different person or thank God for something you see. Walk at a brisk pace between stops." }
  ];

})(typeof window !== 'undefined' ? window : globalThis);
