/* Writing projects for weeks 5–37 (v3). One project every 4 weeks, one stage each Thursday:
   plan → draft → revise → edit and publish. Mon/Tue/Wed/Fri writing time is the daily journal. */
(function (root) {
  'use strict';
  var C = typeof require !== 'undefined' && typeof module !== 'undefined' ? require('./core.js') : root.Content;
  var CHECK = ['Every sentence starts with a capital letter.', 'Every sentence ends with . ? or !', 'Names of people and places are capitalized.', 'I read it out loud and it sounds right.'];

  // Each project: name, intro, and four stages. Stage = { title, intro, demo:{q,steps,a}, fields:[{id,label,min}], checklist }
  C.projects = [
    { start: 5, name: 'Opinion piece: the best place in Georgia', intro: 'For the next four Thursdays you will write an opinion piece. An opinion piece tells what YOU think and gives strong reasons so the reader agrees with you. Your topic: What is the best place in Georgia to visit? (A park, a city, a beach, a museum, even your own backyard.)',
      stages: [
        { title: 'Plan your opinion', intro: 'Pick your place and find three reasons.', demo: { q: 'How do I plan an opinion piece?', steps: ['Step 1: Choose ONE place. Mine is Tybee Island.', 'Step 2: Write my opinion as one clear sentence: "Tybee Island is the best place in Georgia to visit."', 'Step 3: List three reasons: the lighthouse, the sea turtles, and the soft sand beach.', 'Step 4: For each reason, think of a detail or example that proves it.'], a: 'An opinion + three reasons + a detail for each reason.' },
          fields: [{ id: 'place', label: 'Your place (one sentence: "The best place in Georgia to visit is...")', min: 8 }, { id: 'r1', label: 'Reason 1 and a detail that proves it', min: 12 }, { id: 'r2', label: 'Reason 2 and a detail', min: 12 }, { id: 'r3', label: 'Reason 3 and a detail', min: 12 }], checklist: ['My opinion is one clear sentence.', 'I have three different reasons.', 'Each reason has a detail or example.'] },
        { title: 'Write your draft', intro: 'Turn your plan into paragraphs.', demo: { q: 'How do I turn a plan into paragraphs?', steps: ['Step 1: INTRODUCTION: hook the reader, then state your opinion.', 'Step 2: BODY: one paragraph for each reason. Start with a linking word: First, Also, Most of all.', 'Step 3: CONCLUSION: say your opinion again in new words and tell the reader what to do ("Pack your bags for Tybee!").'], a: 'Intro, three reason paragraphs, conclusion.' },
          fields: [{ id: 'intro', label: 'INTRODUCTION: a hook and your opinion (2–3 sentences)', min: 20 }, { id: 'body', label: 'BODY: your three reasons with details (use First, Also, Most of all)', min: 70 }, { id: 'end', label: 'CONCLUSION: restate your opinion and end strong (2–3 sentences)', min: 20 }], checklist: CHECK },
        { title: 'Revise: make it convincing', intro: 'Good writers make their reasons stronger.', demo: { q: 'How do I make an opinion more convincing?', steps: ['Step 1: Read your draft out loud. Where does it sound weak?', 'Step 2: Add a FACT or a number ("Tybee\'s lighthouse is over 140 years old").', 'Step 3: Add a feeling or sense detail ("the warm sand squishes between your toes").', 'Step 4: Swap tired words like "good" and "fun" for exact words.'], a: 'Facts, sense details, and exact words make readers agree.' },
          fields: [{ id: 'fact', label: 'Write one new sentence with a fact or example to add', min: 10 }, { id: 'senses', label: 'Write two sentences with sense details (see, hear, smell, feel, taste)', min: 15 }, { id: 'revised', label: 'Rewrite your whole BODY with the new sentences added', min: 90 }], checklist: ['I added a fact or example.', 'I added sense details.', 'I replaced at least two boring words.'] },
        { title: 'Edit and publish', intro: 'Fix the little things and make a final copy.', demo: { q: 'How do I edit?', steps: ['Step 1: Check capitals at the start of every sentence and on names (Georgia, Tybee).', 'Step 2: Check the end of every sentence for . ? or !', 'Step 3: Circle words that look wrong and fix their spelling.', 'Step 4: Type your final copy with a title.'], a: 'Capitals, punctuation, spelling, then a clean final copy.' },
          fields: [{ id: 'final', label: 'FINAL COPY: title on the first line, then your whole opinion piece', min: 130 }, { id: 'feel', label: 'One sentence: what part are you proudest of?', min: 6 }], checklist: CHECK, publish: true }
      ] },
    { start: 9, name: 'Friendly letters and thank-you notes', intro: 'This month you will write a real letter to someone you love (a grandparent, aunt, friend, or pastor) and a thank-you note. Real letters make people smile, so you will mail them!',
      stages: [
        { title: 'Plan your letter', intro: 'Choose who will get your letter and what you will tell them.', demo: { q: 'What goes in a friendly letter?', steps: ['Step 1: Pick the person. Mine is Grandpa.', 'Step 2: A letter has five parts: the date, a greeting ("Dear Grandpa,"), the body, a closing ("Love,"), and your signature.', 'Step 3: List three things to tell or ask: what I am learning, a funny thing my dog did, and a question about when he was a kid.'], a: 'Date, greeting, body, closing, signature.' },
          fields: [{ id: 'who', label: 'Who is your letter for, and why did you pick them?', min: 12 }, { id: 'ideas', label: 'Three things you will tell or ask them', min: 20 }], checklist: ['I know who my letter is for.', 'I have three things to say or ask.'] },
        { title: 'Write your letter', intro: 'Write the whole letter with all five parts.', demo: { q: 'How should the body sound?', steps: ['Step 1: Start warm: "I hope you are doing well. I miss you!"', 'Step 2: Tell your news in a few sentences each. Add details.', 'Step 3: Ask a question so they want to write back.', 'Step 4: End kindly: "I can\'t wait to see you at Christmas."'], a: 'Warm start, news with details, a question, kind ending.' },
          fields: [{ id: 'greet', label: 'Date and greeting (example: December 14, 2026 / Dear Grandpa,)', min: 4 }, { id: 'body', label: 'BODY of your letter', min: 70 }, { id: 'close', label: 'Closing and signature (example: Love, / Ava)', min: 2 }], checklist: ['The greeting ends with a comma.', 'I asked a question.', 'The closing ends with a comma.'] },
        { title: 'A thank-you note', intro: 'Thank-you notes are short and specific.', demo: { q: 'What makes a great thank-you note?', steps: ['Step 1: Name the gift or kindness exactly: "Thank you for the purple scarf."', 'Step 2: Tell how you use it or why it matters: "I wear it every cold morning."', 'Step 3: Say something kind about them and sign it.'], a: 'Name it, say why it matters, end kindly.' },
          fields: [{ id: 'thanks', label: 'Write a thank-you note to someone (for a gift, help, or kindness)', min: 45 }], checklist: ['I named exactly what I am thankful for.', 'I said why it matters to me.'] },
        { title: 'Edit and mail it', intro: 'Make a clean copy, then copy it by hand onto nice paper and mail it.', demo: { q: 'How do I address an envelope?', steps: ['Step 1: In the middle: the person\'s name, street address, then city, state, and ZIP code.', 'Step 2: In the top-left corner: your name and address.', 'Step 3: A stamp goes in the top-right corner.'], a: 'Their address in the middle, yours top left, stamp top right.' },
          fields: [{ id: 'final', label: 'FINAL COPY of your letter (all five parts)', min: 90 }, { id: 'feel', label: 'One sentence: how do you think they will feel when they open it?', min: 6 }], checklist: CHECK.concat(['I copied it by hand and a parent helped me mail it (or will today).']), publish: true }
      ] },
    { start: 13, name: 'Informative report: an animal of Georgia', intro: 'For four Thursdays you will research one animal that lives in Georgia (like the gopher tortoise, brown thrasher, black bear, right whale, or alligator) and write an informative report. Use library books or articles your parent helps you find.',
      stages: [
        { title: 'Research and take notes', intro: 'Find facts and write them in your own words.', demo: { q: 'How do I take notes without copying?', steps: ['Step 1: Read a short section of your book.', 'Step 2: Close the book.', 'Step 3: Write the fact in your OWN words, in a few words: "eats grass and berries."', 'Step 4: Sort facts into groups: looks, home, food, interesting facts.'], a: 'Read, close the book, write it your way, sort it.' },
          fields: [{ id: 'animal', label: 'Your animal and where you found information (book titles or websites)', min: 8 }, { id: 'looks', label: 'Notes: what it looks like', min: 12 }, { id: 'home', label: 'Notes: where it lives and its habitat', min: 12 }, { id: 'food', label: 'Notes: what it eats and what eats it', min: 12 }, { id: 'cool', label: 'Notes: amazing facts', min: 12 }], checklist: ['I used my own words.', 'I have notes for every group.'] },
        { title: 'Write your draft', intro: 'Each group of notes becomes a paragraph.', demo: { q: 'How does a report go together?', steps: ['Step 1: INTRODUCTION: a hook question ("Did you know some turtles dig burrows 40 feet long?") and what the report is about.', 'Step 2: One paragraph each for looks, home, and food. Start each with a topic sentence.', 'Step 3: CONCLUSION: your most amazing fact and why the animal matters.'], a: 'Intro, one paragraph per topic, conclusion.' },
          fields: [{ id: 'intro', label: 'INTRODUCTION with a hook', min: 20 }, { id: 'body', label: 'BODY: a paragraph for each topic, each with a topic sentence', min: 100 }, { id: 'end', label: 'CONCLUSION', min: 20 }], checklist: CHECK },
        { title: 'Revise: text features and word choice', intro: 'Reports use headings and exact science words.', demo: { q: 'How can I make a report clearer?', steps: ['Step 1: Add a heading above each paragraph (What It Looks Like, Home, Food).', 'Step 2: Use exact words: "burrow" not "hole," "herbivore" not "eats plants."', 'Step 3: Add a "Did you know?" fact box sentence.'], a: 'Headings, exact words, and a fun fact box.' },
          fields: [{ id: 'heads', label: 'Write your three headings', min: 6 }, { id: 'words', label: 'List 3 exact science words you will use and what they mean', min: 15 }, { id: 'revised', label: 'Rewrite your report body with headings and better words', min: 120 }], checklist: ['Every paragraph has a heading.', 'I used at least three exact science words.'] },
        { title: 'Edit and publish', intro: 'Make it ready to share. You can add a drawing on paper.', demo: { q: 'What is a bibliography?', steps: ['Step 1: At the end, list the books or websites you used.', 'Step 2: For a book write: Title, by Author.', 'Step 3: This gives credit to the people whose facts you learned.'], a: 'A list of your sources that gives credit.' },
          fields: [{ id: 'final', label: 'FINAL COPY: title, headings, paragraphs', min: 160 }, { id: 'sources', label: 'Sources: the books or websites you used', min: 4 }], checklist: CHECK.concat(['I listed my sources.']), publish: true }
      ] },
    { start: 17, name: 'Narrative: a story with a problem', intro: 'This month you will write a made-up story with a main character, a problem, and a solution. It can be realistic, funny, or a fantasy adventure.',
      stages: [
        { title: 'Plan the story', intro: 'Every story needs a character, a setting, a problem, and a solution.', demo: { q: 'How do I plan a story?', steps: ['Step 1: CHARACTER: Who? Give them a name and one strong trait (brave, curious, shy).', 'Step 2: SETTING: Where and when?', 'Step 3: PROBLEM: What goes wrong?', 'Step 4: SOLUTION: How does the character fix it (not by magic luck, by their own choices)?'], a: 'Character, setting, problem, solution.' },
          fields: [{ id: 'char', label: 'Main character: name, age, and what they are like', min: 12 }, { id: 'set', label: 'Setting: where and when', min: 8 }, { id: 'prob', label: 'The problem', min: 12 }, { id: 'sol', label: 'How the character solves it', min: 12 }], checklist: ['My character solves the problem with their own choices.'] },
        { title: 'Draft beginning, middle, end', intro: 'Write the story in order.', demo: { q: 'How should my story begin?', steps: ['Step 1: Start in the action or with dialogue, not with "One day."', 'Step 2: MIDDLE: the problem gets harder. Tell it step by step.', 'Step 3: END: the solution, and how the character has changed or what they learned.'], a: 'Action start, growing problem, satisfying end.' },
          fields: [{ id: 'begin', label: 'BEGINNING', min: 35 }, { id: 'middle', label: 'MIDDLE', min: 70 }, { id: 'end', label: 'END', min: 35 }], checklist: CHECK },
        { title: 'Revise: dialogue and showing', intro: 'Show feelings instead of telling them, and let characters talk.', demo: { q: 'What is "show, don\'t tell"?', steps: ['Step 1: TELLING: "Mia was scared."', 'Step 2: SHOWING: "Mia\'s hands shook as she reached for the door."', 'Step 3: Add dialogue: "Who\'s there?" Mia whispered.'], a: 'Show feelings through actions, and use dialogue.' },
          fields: [{ id: 'show', label: 'Rewrite two "telling" sentences from your story as "showing" sentences', min: 20 }, { id: 'talk', label: 'Write 3 lines of dialogue with quotation marks', min: 15 }, { id: 'revised', label: 'Rewrite your MIDDLE with showing and dialogue', min: 90 }], checklist: ['I used quotation marks correctly.', 'I showed at least one feeling.'] },
        { title: 'Edit and publish', intro: 'Give it a title and make the final copy.', demo: { q: 'How do I pick a great title?', steps: ['Step 1: Think of the most interesting thing in the story.', 'Step 2: Make it short and curious: "The Key Under the Porch."', 'Step 3: Capitalize the important words in the title.'], a: 'Short, curious, capitalized.' },
          fields: [{ id: 'final', label: 'FINAL COPY with a title', min: 180 }, { id: 'feel', label: 'One sentence: what did you enjoy most about writing it?', min: 6 }], checklist: CHECK, publish: true }
      ] },
    { start: 21, name: 'Opinion essay with evidence (5th grade)', intro: 'Fifth graders support opinions with evidence, not just reasons. Your question: Should kids your age have daily chores? Decide what you think, then prove it.',
      stages: [
        { title: 'Claim and evidence', intro: 'A claim is your opinion. Evidence is proof.', demo: { q: 'What counts as evidence?', steps: ['Step 1: CLAIM: "Kids should have daily chores."', 'Step 2: REASON: "Chores teach responsibility."', 'Step 3: EVIDENCE: an example, a fact, or something an expert or adult said ("My mom says...").', 'Step 4: Plan two or three reasons, each with evidence.'], a: 'Claim, reasons, and proof for each reason.' },
          fields: [{ id: 'claim', label: 'Your claim (one sentence)', min: 8 }, { id: 'r1', label: 'Reason 1 + evidence', min: 18 }, { id: 'r2', label: 'Reason 2 + evidence', min: 18 }, { id: 'counter', label: 'What would someone who disagrees say?', min: 12 }], checklist: ['Every reason has evidence.'] },
        { title: 'Draft the essay', intro: 'Five paragraphs: intro, two or three reasons, a response to the other side, conclusion.', demo: { q: 'How do I answer the other side?', steps: ['Step 1: Say it fairly: "Some people think chores take time away from homework."', 'Step 2: Answer it: "However, most chores take only 15 minutes."', 'Step 3: This makes your argument stronger, not weaker.'], a: 'State the other side fairly, then answer it.' },
          fields: [{ id: 'intro', label: 'INTRODUCTION with your claim', min: 25 }, { id: 'body', label: 'BODY: reasons with evidence', min: 100 }, { id: 'counter', label: 'The other side and your answer', min: 30 }, { id: 'end', label: 'CONCLUSION', min: 25 }], checklist: CHECK },
        { title: 'Revise: transitions', intro: 'Transitions connect your ideas smoothly.', demo: { q: 'Which transitions should I use?', steps: ['To add: also, in addition, furthermore.', 'To give an example: for example, for instance.', 'To show the other side: however, on the other hand.', 'To conclude: in conclusion, for these reasons.'], a: 'Use transitions to guide the reader.' },
          fields: [{ id: 'trans', label: 'Write 4 sentences from your essay that now start with a transition', min: 30 }, { id: 'revised', label: 'Rewrite your BODY with transitions', min: 110 }], checklist: ['I used at least four transitions.'] },
        { title: 'Edit and publish', intro: 'Read it aloud to your family as a speech!', demo: { q: 'How do I edit like a 5th grader?', steps: ['Check capitals and end marks.', 'Check commas after transitions ("However, ...").', 'Check that verb tenses stay the same.', 'Read it aloud slowly.'], a: 'Capitals, commas, verb tenses, read aloud.' },
          fields: [{ id: 'final', label: 'FINAL COPY with a title', min: 200 }], checklist: CHECK.concat(['I read it aloud to my family.']), publish: true }
      ] },
    { start: 25, name: 'Biography report: a person I admire', intro: 'Pick a real person from history you admire (for example, a scientist, inventor, pastor, explorer, or civil-rights leader from your social studies lessons). You will research their life and write a biography report.',
      stages: [
        { title: 'Research their life', intro: 'Take notes in your own words.', demo: { q: 'What do I research?', steps: ['Early life: when and where they were born, their family.', 'Big challenges they faced.', 'What they did that mattered.', 'Why people remember them today.'], a: 'Early life, challenges, accomplishments, legacy.' },
          fields: [{ id: 'who', label: 'Person and your sources', min: 8 }, { id: 'early', label: 'Notes: early life', min: 15 }, { id: 'chal', label: 'Notes: challenges', min: 15 }, { id: 'acc', label: 'Notes: accomplishments', min: 15 }], checklist: ['I used my own words.', 'I wrote down my sources.'] },
        { title: 'Draft in time order', intro: 'Biographies usually go in the order things happened.', demo: { q: 'How do I keep events in order?', steps: ['Use dates and time words: In 1890, Later, After that, Finally.', 'Start with an interesting moment, then go back to their childhood.', 'End with why they matter.'], a: 'Dates and time words keep it in order.' },
          fields: [{ id: 'intro', label: 'INTRODUCTION: a hook about this person', min: 25 }, { id: 'body', label: 'BODY: their life in time order', min: 120 }, { id: 'end', label: 'CONCLUSION: why they matter and what you learned from them', min: 30 }], checklist: CHECK },
        { title: 'Revise: add a quote and a timeline', intro: 'Real facts make a biography trustworthy.', demo: { q: 'How do I use a quote?', steps: ['Find something the person really said (from your book).', 'Copy it exactly inside quotation marks.', 'Tell who said it and why it matters.'], a: 'Exact words, in quotation marks, with who said it.' },
          fields: [{ id: 'timeline', label: 'A timeline: 5 dates and what happened', min: 25 }, { id: 'revised', label: 'Rewrite your BODY with at least one quote or exact fact added', min: 130 }], checklist: ['Every date is correct from my sources.'] },
        { title: 'Edit and publish', intro: 'Make the final copy.', demo: { q: 'Last checks?', steps: ['Capitals on names, places, and months.', 'Commas in dates (July 4, 1776).', 'Sources listed at the end.'], a: 'Names, dates, sources.' },
          fields: [{ id: 'final', label: 'FINAL COPY with a title', min: 220 }, { id: 'sources', label: 'Sources', min: 4 }], checklist: CHECK, publish: true }
      ] },
    { start: 29, name: 'Poetry collection', intro: 'This month you will write a small book of four poems: an acrostic, a haiku, a cinquain, and a free-verse poem about something you love.',
      stages: [
        { title: 'Acrostic and haiku', intro: 'Two short forms to warm up.', demo: { q: 'What are an acrostic and a haiku?', steps: ['ACROSTIC: write a word down the side (SUMMER). Each line starts with that letter.', 'HAIKU: three lines with 5, 7, and 5 syllables, usually about nature.', 'Example haiku: Morning fog lifting (5) / a heron steps through the reeds (7) / slow as a sunrise (5).'], a: 'Acrostic: first letters spell a word. Haiku: 5-7-5 syllables.' },
          fields: [{ id: 'acro', label: 'Your acrostic poem (pick a word with 5+ letters)', min: 15 }, { id: 'haiku', label: 'Your haiku (5-7-5)', min: 8 }], checklist: ['My haiku has 5, 7, 5 syllables.'] },
        { title: 'Cinquain', intro: 'A cinquain is a five-line poem shaped like a diamond tip.', demo: { q: 'How do I write a cinquain?', steps: ['Line 1: one word (the topic): Rain', 'Line 2: two describing words: Soft, silver', 'Line 3: three action words: tapping, dripping, singing', 'Line 4: a four-word feeling: makes me feel cozy', 'Line 5: one word that renames the topic: Lullaby'], a: '1-2-3-4-1 words.' },
          fields: [{ id: 'cin1', label: 'Cinquain #1', min: 10 }, { id: 'cin2', label: 'Cinquain #2', min: 10 }], checklist: ['Each line has the right number of words.'] },
        { title: 'Free verse', intro: 'Free verse does not have to rhyme. It uses images, line breaks, and strong words.', demo: { q: 'How do I write free verse?', steps: ['Pick something you love (a person, a place, a pet).', 'Write what you see, hear, and feel, one image per line.', 'Use a simile or personification ("the wind tugs my sleeve").', 'End with a line that surprises or sums it up.'], a: 'Images, line breaks, figurative language, a strong ending.' },
          fields: [{ id: 'free', label: 'Your free-verse poem (at least 8 lines)', min: 40 }], checklist: ['I used at least one simile or personification.'] },
        { title: 'Publish your poetry book', intro: 'Choose your best versions, give the collection a title, and copy it into a little paper book with drawings.', demo: { q: 'How do I put a poetry book together?', steps: ['Make a title page with the collection name and your name.', 'One poem per page with a drawing.', 'Read your favorite one aloud to your family.'], a: 'Title page, one poem per page, read it aloud.' },
          fields: [{ id: 'final', label: 'FINAL COPY: title of your collection, then all four poems', min: 80 }, { id: 'feel', label: 'Which poem is your favorite and why?', min: 10 }], checklist: ['All four poems are included.', 'I read one aloud to my family.'], publish: true }
      ] },
    { start: 33, name: 'How-to guide: something I am good at', intro: 'Everyone is an expert at something. This month you will write a how-to guide that teaches a reader to do something you know well (bake cookies, care for a pet, braid hair, draw a horse).',
      stages: [
        { title: 'Plan the steps', intro: 'A how-to guide needs materials and clear steps in order.', demo: { q: 'How do I plan a how-to guide?', steps: ['Step 1: Name the task and why it is worth learning.', 'Step 2: List all the materials.', 'Step 3: Write the steps in order. Act it out to check you did not skip one.'], a: 'Task, materials, steps in order.' },
          fields: [{ id: 'task', label: 'What will you teach, and why is it worth learning?', min: 12 }, { id: 'mat', label: 'Materials list', min: 6 }, { id: 'steps', label: 'Steps in order (number them)', min: 30 }], checklist: ['I acted out the steps to check them.'] },
        { title: 'Draft the guide', intro: 'Write it so a beginner can follow it.', demo: { q: 'What makes steps easy to follow?', steps: ['Start each step with an action verb: Mix, Fold, Pour.', 'Use order words: First, Next, Then, Finally.', 'Add a tip or warning where it helps ("Ask an adult to use the oven").'], a: 'Action verbs, order words, tips.' },
          fields: [{ id: 'intro', label: 'INTRODUCTION', min: 20 }, { id: 'body', label: 'STEPS written in full sentences', min: 90 }, { id: 'end', label: 'CONCLUSION: how the reader will feel when they finish', min: 15 }], checklist: CHECK },
        { title: 'Revise: test it on someone', intro: 'Have a family member follow your guide exactly while you watch.', demo: { q: 'How do I test a how-to guide?', steps: ['Give your guide to a family member.', 'Watch where they get confused.', 'Add or fix those steps.'], a: 'Watch someone use it, then fix the confusing parts.' },
          fields: [{ id: 'test', label: 'Who tested it and where did they get confused?', min: 15 }, { id: 'revised', label: 'Rewrite the steps with your fixes', min: 100 }], checklist: ['Someone tested my guide.'] },
        { title: 'Edit and publish', intro: 'Final copy, with a title and a drawing of the finished result.', demo: { q: 'Last checks?', steps: ['Every step starts with a capital letter and ends with a period.', 'Numbers or order words are in the right order.', 'Title is capitalized.'], a: 'Clean, numbered, capitalized.' },
          fields: [{ id: 'final', label: 'FINAL COPY', min: 150 }], checklist: CHECK, publish: true }
      ] }
  ];
  // week 37: celebration
  C.projectFinale = { title: 'Writing celebration: my best piece', intro: 'Look back at everything you wrote this year. Choose your favorite piece, polish it one more time, and share it with your family.',
    demo: { q: 'How do I choose my best piece?', steps: ['Read your final copies from this year.', 'Pick the one you are proudest of.', 'Fix anything you now know how to do better.', 'Read it aloud at dinner.'], a: 'Choose, polish, share.' },
    fields: [{ id: 'which', label: 'Which piece did you choose, and why?', min: 15 }, { id: 'final', label: 'The polished final copy', min: 120 }, { id: 'grow', label: 'How has your writing grown this year?', min: 20 }], checklist: CHECK.concat(['I shared it with my family.']), publish: true };

  if (typeof module !== 'undefined' && module.exports) module.exports = C.projects;
})(typeof window !== 'undefined' ? window : globalThis);
